// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setYCoordsFUN
DataFrame setYCoordsFUN(DataFrame df);
RcppExport SEXP _haploplotR_setYCoordsFUN(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(setYCoordsFUN(df));
    return rcpp_result_gen;
END_RCPP
}
// toRawSnpMat
RawMatrix toRawSnpMat(IntegerMatrix ishet, IntegerMatrix hasalt);
RcppExport SEXP _haploplotR_toRawSnpMat(SEXP ishetSEXP, SEXP hasaltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ishet(ishetSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type hasalt(hasaltSEXP);
    rcpp_result_gen = Rcpp::wrap(toRawSnpMat(ishet, hasalt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_haploplotR_setYCoordsFUN", (DL_FUNC) &_haploplotR_setYCoordsFUN, 1},
    {"_haploplotR_toRawSnpMat", (DL_FUNC) &_haploplotR_toRawSnpMat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_haploplotR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
