// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setYCoordsFUN
DataFrame setYCoordsFUN(DataFrame df);
RcppExport SEXP haploplotR_setYCoordsFUN(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    __result = Rcpp::wrap(setYCoordsFUN(df));
    return __result;
END_RCPP
}
// toRawSnpMat
RawMatrix toRawSnpMat(IntegerMatrix ishet, IntegerMatrix hasalt);
RcppExport SEXP haploplotR_toRawSnpMat(SEXP ishetSEXP, SEXP hasaltSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ishet(ishetSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type hasalt(hasaltSEXP);
    __result = Rcpp::wrap(toRawSnpMat(ishet, hasalt));
    return __result;
END_RCPP
}
