# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' internal functions used in genesGrob to specify y position of transcripts
#' @name setYCoordsFUN
#' @param txs GRanges or IRanges object specifying start and end postitions of transcripts
#' @return integer vector indicating y postions of transcripts
#' @examples
#' where <- GRanges(Rle('chr1'), IRanges(start = 209789729, end = 210189729))
#' COMPLETE EXAMPLE
NULL

setYCoordsFUN <- function(df) {
    .Call('haploplotR_setYCoordsFUN', PACKAGE = 'haploplotR', df)
}

#' Create matrix with type Raw from matrices describing heterogeneity and presence of the alternative allele
#' @name toRawSnpMat
#' @param ishet Integer matrix describing heterogeneity
#' @param hasalt Integer matrix describing whether or not the alternaive allele is present.
#' @return matrix A matrix of encoding the genotype as type Raw. 01 homozygous reference allele, 02 heterozygous, 03 homozygous alternative allele, 04 missing and else.
NULL

toRawSnpMat <- function(ishet, hasalt) {
    .Call('haploplotR_toRawSnpMat', PACKAGE = 'haploplotR', ishet, hasalt)
}

